version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    volumes:
      - my-db:/var/lib/mysql
      - ./MySql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      timeout: 20s
      retries: 10

  app:
    container_name: app
    restart: on-failure
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  my-db:
